"""
Writer — generates .claude/hygiene.md that Claude reads automatically on session start.
Also generates stdout output for hook injection.
"""

import os
from datetime import datetime
from pathlib import Path
from typing import Dict, Any, Optional


def write_hygiene_md(session: Dict[str, Any], project_dir: Optional[str] = None) -> str:
    """Write session context to .claude/hygiene.md so Claude auto-reads it.

    Returns the path written to.
    """
    if not project_dir:
        project_dir = session.get("working_directory", os.getcwd())

    claude_dir = Path(project_dir) / ".claude"
    claude_dir.mkdir(parents=True, exist_ok=True)
    filepath = claude_dir / "hygiene.md"

    content = _render_markdown(session)
    filepath.write_text(content)
    return str(filepath)


def render_hook_output(session: Dict[str, Any]) -> str:
    """Render session context for hook stdout injection into Claude's context."""
    lines = [
        f"# Resumed Session: {session.get('session_id', 'unknown')}",
        "",
        f"**Task:** {session.get('task', 'No description')}",
        f"**Status:** {session.get('status', 'Unknown')}",
        f"**Saved:** {session.get('timestamp', 'unknown')}",
        f"**Directory:** {session.get('working_directory', 'unknown')}",
    ]

    git = session.get("git", {})
    if git.get("branch"):
        lines.append(f"**Branch:** {git['branch']}")

    decisions = session.get("decisions", [])
    if decisions:
        lines.extend(["", "## Decisions"])
        for d in decisions[:10]:
            lines.append(f"- {d}")

    all_files = set(
        git.get("modified_files", [])
        + git.get("staged_files", [])
        + git.get("untracked_files", [])
    )
    if all_files:
        lines.extend(["", "## Files in Flight"])
        for f in sorted(all_files)[:15]:
            lines.append(f"- {f}")

    if git.get("recent_commits"):
        lines.extend(["", "## Recent Commits"])
        for c in git["recent_commits"][:5]:
            lines.append(f"- {c}")

    lines.extend([
        "",
        "Continue from where this session left off. "
        "Refer to the task and decisions above for context.",
    ])

    return "\n".join(lines)


def _render_markdown(session: Dict[str, Any]) -> str:
    """Render full session as markdown for .claude/hygiene.md."""
    lines = [
        "# Session Context (Novyx Hygiene)",
        "",
        "> Auto-generated by `novyx-hygiene`. Do not edit manually.",
        f"> Last saved: {session.get('timestamp', 'unknown')}",
        "",
        f"## Task",
        "",
        session.get("task", "No description"),
        "",
        f"**Status:** {session.get('status', 'Unknown')}",
        f"**Session ID:** {session.get('session_id', 'unknown')}",
    ]

    git = session.get("git", {})
    if git.get("branch"):
        lines.append(f"**Branch:** {git['branch']}")

    decisions = session.get("decisions", [])
    if decisions:
        lines.extend(["", "## Key Decisions", ""])
        for i, d in enumerate(decisions[:10], 1):
            lines.append(f"{i}. {d}")

    all_files = set(
        git.get("modified_files", [])
        + git.get("staged_files", [])
        + git.get("untracked_files", [])
    )
    if all_files:
        lines.extend(["", "## Files in Flight", ""])
        staged = set(git.get("staged_files", []))
        modified = set(git.get("modified_files", []))
        for f in sorted(all_files)[:20]:
            marker = ""
            if f in staged:
                marker = " (staged)"
            elif f in modified:
                marker = " (modified)"
            else:
                marker = " (new)"
            lines.append(f"- `{f}`{marker}")

    if git.get("recent_commits"):
        lines.extend(["", "## Recent Commits", ""])
        for c in git["recent_commits"][:5]:
            lines.append(f"- {c}")

    lines.extend([
        "",
        "## Instructions",
        "",
        "Continue from where this session left off. "
        "The task, decisions, and file list above represent the current working state.",
    ])

    return "\n".join(lines) + "\n"
